/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './__root'
import { Route as MyTracksRouteImport } from './my-tracks'
import { Route as MyPlaylistRouteImport } from './my-playlist'
import { Route as IndexRouteImport } from './index'
import { Route as OauthCallbackRouteImport } from './oauth/callback'

const MyTracksRoute = MyTracksRouteImport.update({
  id: '/my-tracks',
  path: '/my-tracks',
  getParentRoute: () => rootRouteImport,
} as any)
const MyPlaylistRoute = MyPlaylistRouteImport.update({
  id: '/my-playlist',
  path: '/my-playlist',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthCallbackRoute = OauthCallbackRouteImport.update({
  id: '/oauth/callback',
  path: '/oauth/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/my-playlist': typeof MyPlaylistRoute
  '/my-tracks': typeof MyTracksRoute
  '/oauth/callback': typeof OauthCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/my-playlist': typeof MyPlaylistRoute
  '/my-tracks': typeof MyTracksRoute
  '/oauth/callback': typeof OauthCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/my-playlist': typeof MyPlaylistRoute
  '/my-tracks': typeof MyTracksRoute
  '/oauth/callback': typeof OauthCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/my-playlist' | '/my-tracks' | '/oauth/callback'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/my-playlist' | '/my-tracks' | '/oauth/callback'
  id: '__root__' | '/' | '/my-playlist' | '/my-tracks' | '/oauth/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MyPlaylistRoute: typeof MyPlaylistRoute
  MyTracksRoute: typeof MyTracksRoute
  OauthCallbackRoute: typeof OauthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/my-tracks': {
      id: '/my-tracks'
      path: '/my-tracks'
      fullPath: '/my-tracks'
      preLoaderRoute: typeof MyTracksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-playlist': {
      id: '/my-playlist'
      path: '/my-playlist'
      fullPath: '/my-playlist'
      preLoaderRoute: typeof MyPlaylistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth/callback': {
      id: '/oauth/callback'
      path: '/oauth/callback'
      fullPath: '/oauth/callback'
      preLoaderRoute: typeof OauthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MyPlaylistRoute: MyPlaylistRoute,
  MyTracksRoute: MyTracksRoute,
  OauthCallbackRoute: OauthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
