import createClient, {type Middleware} from "openapi-fetch";
import type { paths } from "./schema"; // generated by openapi-typescript

export const client = createClient<paths>({ baseUrl: import.meta.env.VITE_BACKEND_URL,headers:{
    "api-key":`${import.meta.env.VITE_API_TOKEN}`
} });

let refreshTokenPromise: Promise<void> | null = null
function makeRefreshToken () {
    if (!refreshTokenPromise) {
        refreshTokenPromise = (async (): Promise<void> => {
            const refreshToken = localStorage.getItem("musicfun-refresh-token")
            if(!refreshToken) throw new Error("no refresh token")

            const response = await fetch(import.meta.env.VITE_BACKEND_URL + "auth/refresh", {
                method:"POST",
                headers: {
                    "Content-Type": "application/json",
                    "API-KEY": `${import.meta.env.VITE_API_TOKEN}`
                },
                body: JSON.stringify({
                    refreshToken: refreshToken
                })
            })
            if (!response.ok) {
                localStorage.removeItem("musicfun-access-token")
                localStorage.removeItem("musicfun-refresh-token")
                throw new Error("Refresh token failed")
            }
            const data = await response.json();
            localStorage.setItem("musicfun-access-token",data.accessToken)
            localStorage.setItem("musicfun-refresh-token",data.refreshToken)
        })()
        refreshTokenPromise.finally(() => {
            refreshTokenPromise = null
        })
        return refreshTokenPromise
    }
}
const authMiddleware: Middleware = {
    onRequest({ request}) {
        request.headers.set("foo", "bar");
        const accessToken = localStorage.getItem("musicfun-access-token")
        if(accessToken) {
            request.headers.set("Authorization", "Bearer " + accessToken)
        }
        //@ts-expect-error hot fix
        request._retryRequest = request.clone()
        return request;
    },
    async onResponse({request, response }) {
        if (response.ok) return response;

        if (!response.ok && response.status !== 401) {
            // Will produce error messages like "https://example.org/api/v1/example: 404 Not Found".
            throw new Error(`${response.url}: ${response.status} ${response.statusText}`)
        }
        try {
            await makeRefreshToken()
            //@ts-expect-error hot fix
            const originalRequest:Request = request._retryRequest
            const retryReq = new Request(originalRequest, {headers: new Headers(originalRequest.headers)})
            retryReq.headers.set("Authorization","Bearer " + localStorage.getItem("musicfun-access-token"))
            return fetch(retryReq)
        } catch {
            return response;
        }
    }
};
client.use(authMiddleware)